cues:
  - action: fade
    at: 3
    devices:
      - main_light
      - overhead_light_2
    duration: 10
    to_brightness: 100
  - action: fade
    at: 3
    devices:
      - spotlight_1
      - spotlight_2
      - spotlight_3
    duration: 10
    to_brightness: 70
  - action: "off"
    at: 10
    devices:
      - stage_switch
  - action: fade
    at: 98
    devices:
      - main_light
      - overhead_light_2
    duration: 8
    to_brightness: 1
  - action: fade
    at: 98
    devices:
      - spotlight_1
      - spotlight_2
      - spotlight_3
    duration: 8
    to_brightness: 1
  - action: "on"
    at: 103
    devices:
      - stage_switch
  - action: "off"
    at: 108
    devices:
      - spotlight_1
      - spotlight_2
      - spotlight_3
  - action: "off"
    at: 108
    devices:
      - main_light
      - overhead_light_2
devices:
  main_light:
    initial_state:
      true: true
      brightness: 1
    ip: 192.168.8.105
    type: l530
  overhead_light_2:
    initial_state:
      true: true
      brightness: 1
    ip: 192.168.8.104
    type: l530
  spotlight_1:
    initial_state:
      true: false
      brightness: 1
    ip: 192.168.8.103
    type: l630
  spotlight_2:
    initial_state:
      true: false
      brightness: 1
    ip: 192.168.8.101
    type: l630
  spotlight_3:
    initial_state:
      true: false
      brightness: 1
    ip: 192.168.8.100
    type: l630
  stage_switch:
    initial_state:
      true: true
    ip: 192.168.8.102
    type: p100
dry_run: false
video:
  fullscreen: true
  loop: true
  screens:
    - monitor: 1
      mute: true
      path: Full_Day_Sequence_B.mp4
      window_title: Screen 1
    - monitor: 2
      mute: false
      path: Full_Day_Sequence_A.mp4
      window_title: Screen 2
