dry_run: false  # set to true to play videos without triggering any device cues

video:
  loop: true
  fullscreen: false
  screens:
    - path: "earth_turning.mp4"
      window_title: "Screen 1"
      monitor: 0
    - path: "earth_turning.mp4"
      window_title: "Screen 2"
      monitor: 1

devices:
  main_light:
    type: l530
    ip: "192.168.0.156"
    initial_state:
      on: true
      brightness: 100
      hue: 30
      saturation: 80

  stage_switch:
    type: p100
    ip: "192.168.0.160"
    initial_state:
      on: false

cues:
  - at: 5
    device: main_light
    action: fade
    to_brightness: 20
    to_hue: 200
    to_saturation: 100
    duration: 5.0

  - at: 10
    device: stage_switch
    action: "on"

  - at: 20
    device: main_light
    action: set_light
    brightness: 80
    hue: 120
    saturation: 60

  - at: 29
    device: stage_switch
    action: "off"
